// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package server

import (
	"context"

	"github.com/chernyakoff/telemon/account/internal/logic"
	"github.com/chernyakoff/telemon/account/internal/svc"
	"github.com/chernyakoff/telemon/account/types/account"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	account.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) Upsert(ctx context.Context, in *account.AccountUpsertRequest) (*account.MessageResponse, error) {
	l := logic.NewUpsertLogic(ctx, s.svcCtx)
	return l.Upsert(in)
}

func (s *AccountServer) Update(ctx context.Context, in *account.AccountUpdateRequest) (*account.MessageResponse, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *AccountServer) Get(ctx context.Context, in *account.AccountGetRequest) (*account.AccountGetResponse, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

func (s *AccountServer) GetAny(ctx context.Context, in *account.AccountGetAnyRequest) (*account.AccountGetResponse, error) {
	l := logic.NewGetAnyLogic(ctx, s.svcCtx)
	return l.GetAny(in)
}
