// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/chernyakoff/telemon/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: PingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/upsert",
				Handler: AccountUpsertHandler(serverCtx),
			},
		},
	)
}
